[package]
name = "meerkateer-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
actix-web.workspace = true
anyhow.workspace = true
chrono.workspace = true
meerkateer-config = { path = "../crates/meerkateer-config" }
meerkateer-identity = { path = "../crates/meerkateer-identity" }
meerkateer-protocol = { path = "../crates/meerkateer-protocol" }
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
subtle.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
