#!/bin/sh
set -eu

if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload || true
fi

if [ "$1" = purge ]; then
  rm -rf /var/lib/meerkateer-controller
  if getent passwd meerkateer-controller >/dev/null; then
    deluser --system meerkateer-controller >/dev/null 2>&1 || true
  fi
  if getent group meerkateer-controller >/dev/null; then
    delgroup --system meerkateer-controller >/dev/null 2>&1 || true
  fi
fi
